//
// Created by thomas on 20/05/20.
//

#ifndef PLUGINIZED_BIRD_COMMON_EXT_COMM_H
#define PLUGINIZED_BIRD_COMMON_EXT_COMM_H

#define EXTENDED_COMMUNITIES 16u

#endif //PLUGINIZED_BIRD_COMMON_EXT_COMM_H
