//
// Created by thomas on 3/06/20.
//

#ifndef PLUGINIZED_BIRD_COMMON_DATACENTER_H
#define PLUGINIZED_BIRD_COMMON_DATACENTER_H

#define AS_PATH_ATTR_CODE 2

#endif //PLUGINIZED_BIRD_COMMON_DATACENTER_H
